name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip and install pdoc
        run: |
          python -m pip install --upgrade pip
          pip install pdoc

      - name: Generate documentation using pdoc (Google style)
        run: |
          pdoc pyrobale --output-dir docs --docformat google

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.DOCS_DEPLOY_SSH_KEY }}


      - name: Clone docs repository via SSH
        run: git clone git@github.com:daradege/docs.git docs-repo

      - name: Copy generated docs to docs repo
        run: |
          rm -rf docs-repo/*
          cp -r docs/* docs-repo/

      - name: Commit and push docs changes
        working-directory: docs-repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          git diff --quiet && echo "No changes detected, skipping commit" || git commit -m "Update docs [skip ci]"
          git push origin main
